module.exports = {
	api: [{
		id: "",
		name: "",
		path: "/api/imageUpload/upload",
		class: "ImageUpload",
		function: "upload",
		describe: "图片上传"
	}, {
		id: "",
		name: "",
		path: "/api/enterprise/add",
		class: "enterprise",
		function: "add",
		describe: "添加企业基本信息"
	}, {
		id: "",
		name: "",
		path: "/api/product/addType",
		class: "product",
		function: "addType",
		describe: "添加产品类别"
	}, {
		id: "",
		name: "",
		path: "/api/product/getTypeList",
		class: "product",
		function: "getTypeList",
		describe: "获取全部产品类别"
	}, {
		id: "",
		name: "",
		path: "/api/product/addParent",
		class: "product",
		function: "addParent",
		describe: "添加成品"
	}, {
		id: "",
		name: "",
		path: "/api/product/ProductList",
		class: "product",
		function: "ProductList",
		describe: "获取产品列表"
	}, {
		id: "",
		name: "",
		path: "/api/connection/Add",
		class: "connection",
		function: "Add",
		describe: "添加企业联系信息"
	}, {
		id: "",
		name: "",
		path: "/api/connection/Edit",
		class: "connection",
		function: "Edit",
		describe: "编辑企业联系方式"
	}, {
		id: "",
		name: "",
		path: "/api/connection/getInfoMation",
		class: "connection",
		function: "getInfoMation",
		describe: "获取企业信息"
	}, {
		id: "",
		name: "",
		path: "/api/apiSupervise/addWorkQueue",
		class: "apiSupervise",
		function: "addWorkQueue",
		describe: "Http链接管理"
	}]
}